# Wazuh - Filebeat configuration file
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: https
  username: "admin"
  password: "admin"
  ssl.verification_mode: none
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.overwrite: true
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false
